title: Deep Ocean Data team page
description: Ocean Life research using ML, Bigdata and other cool stuff
url                      : https://github.com/deepoceandata/deepoceandata.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : https://github.com/deepoceandata/
google_analytics:
plugins:
  - jekyll-remote-theme
remote_theme: ngzhio/jekyll-theme-hamilton
skin: daylight
# Site Author
author: Deep Ocean Data team
name             : Deep Ocean Data
email : email@email.org
avatar           : /profile.png
# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 
  card: summary
logo: profile.png
